spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:otus17}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      encoding: UTF-8

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate

    show-sql: false

  h2:
    console:
      enabled: false
server:
  servlet:
    context-path: /api
  port: 8081

logging:
  level:
    root: INFO
  file:
    name: otus_app.log
management:
  endpoints:
    web:
      exposure:
        include: health,loggers
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
#JWT
jwt:
  token:
    secret: ${JWT_SECRET:secret}
    expired: 3600000
