spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/otus17
    username: root
    password: root
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      encoding: UTF-8

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate

    show-sql: false

  h2:
    console:
      enabled: false
  port: 8080

logging:
  level:
    root: INFO
  file:
    name: otus_app.log
management:
  endpoints:
    web:
      exposure:
        include: health,loggers
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
#JWT
jwt:
  token:
    secret: secret
    expired: 3600000
