spring:
  data:
    mongodb:
      host: localhost
      port: 0
      database: bookdb
mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.zotov.hw16.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

management:
  endpoints:
    web:
      exposure:
        include: health,loggers
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
