apiVersion: v1
kind: Secret
metadata:
  name: store-carracing-secret
type: Opaque
data:
  DATABASE_URI: {{ printf "jdbc:postgresql://%s:%s@%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase  | b64enc | quote }}
  DB_HOST: {{ (include "postgresql.fullname" .) | b64enc | quote}}
  DB_PORT: {{ .Values.postgresql.service.port | b64enc | quote }}
  DB_NAME: {{ .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  DB_USERNAME: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  DB_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  KAFKA_HOST: {{ (include "kafka.fullname" .) | b64enc | quote }}
  KAFKA_PORT: {{ .Values.kafka.port | b64enc | quote }}
