apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "carapp.fullname" . }}
  labels:
    {{- include "carapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "carapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "carapp.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: carracing-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: carracing-secret
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: carracing-secret
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: carracing-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: carracing-secret
                  key: DB_PASSWORD
            - name: KAFKA_HOST
              valueFrom:
                secretKeyRef:
                  name: carracing-secret
                  key: KAFKA_HOST
            - name: KAFKA_PORT
              valueFrom:
                secretKeyRef:
                  name: carracing-secret
                  key: KAFKA_PORT
          imagePullPolicy: {{ .Values.image.pullPolicy }}
