spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: example
      port: 27017
      host: localhost
      database: bookdb
mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.zotov.hw12.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
#JWT
jwt:
  token:
    secret: secret
    expired: 3600000
