replicaCount: 2

image:
  repository: profile-carracing
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: NodePort
  port: 9000
  targetPort: 8084

ingress:
  enabled: true
  hosts:
    - host: arch.homework
      paths: ["/profile"]

postgresql:
  enabled: true
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: carracing-otus
  service:
    port: "5432"
  persistence:
    size: 1Gi

metrics:
  serviceMonitor:
    enabled: true
kafka:
  enabled: true
  port: "9092"
