{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "carapp.fullname" . }}
  labels:
  {{- include "carapp.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "carapp.fullname" . }}
  namespaceSelector:
    matchNames:
      - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
  {{- include "carapp.selectorLabels" . | nindent 6 }}
  endpoints:
    - interval: 15s
      port: web
      path: /api/v1/metrics/prometheus
  {{- end }}
