CREATE TABLE store_schema.purchase
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id     BIGINT,
    count          INTEGER,
    purchase_date  TIMESTAMP with time zone,
    validate_state INTEGER,
    token          VARCHAR(1000)
);

ALTER TABLE store_schema.purchase
    ADD CONSTRAINT FK_PURCHASE_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES store_schema.spr_product (id);
CREATE INDEX purchase_external_id_idx ON store_schema.purchase (validate_state);
