spring:
  datasource:
    url: jdbc:h2:mem:bookdb

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      encoding: UTF-8

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate

    show-sql: false

logging:
  level:
    root: INFO
  file:
    name: otus_app.log

server:
  port: 8081
