apiVersion: skaffold/v2beta2
kind: Config
build:
  tagPolicy:
    sha256: { }
  artifacts:
    - image: auth-carracing
      context: artifacts/auth
    - image: race-carracing
      context: artifacts/race
    - image: wallet-carracing
      context: artifacts/wallet
    - image: anticheat-carracing
      context: artifacts/anticheat
    - image: profile-carracing
      context: artifacts/profile
    - image: store-carracing
      context: artifacts/store
    - image: mail-carracing
      context: artifacts/mail
deploy:
#  kubectl:
#    manifests:
#      - kubectl/*.yaml
  helm:
    releases:
      - name: carracing
        chartPath: carracing_chart
        skipBuildDependencies: true
