spring:
  datasource:
    url: jdbc:h2:mem:bookdb

  sql:
    init:
      mode: always
      data-locations: data.sql
      encoding: UTF-8

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
      enabled: true
